services:
  - type: web
    name: darkforest-interactive
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: "gunicorn --bind=0.0.0.0:$PORT --log-level debug --timeout 120 --workers 1 app:app"
    pythonVersion: 3.11.8
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: STARWEAVER_CONSUMER_KEY
        sync: false
      - key: STARWEAVER_CONSUMER_SECRET
        sync: false
      - key: STARWEAVER_ACCESS_TOKEN
        sync: false
      - key: STARWEAVER_ACCESS_TOKEN_SECRET
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false